# Use a lightweight Java 17 base image
FROM openjdk:17-jdk-slim

# Create a directory for the app
WORKDIR /app

# Copy the Maven-built jar to the container
COPY target/user-profile-service-0.0.1-SNAPSHOT.jar user-profile-service.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "user-profile-service.jar"]